### PR TITLE
add max website to gallery

### PR DESCRIPTION
**Pull request by maxferlauto**
Thanks for the invite and great theme! Hope I did this right

### CODE REVIEW

**Comment by apreshill** [comment]
We'll see! Does this look good? https://deploy-preview-94--hugo-apero-docs.netlify.app/project/

**Comment by apreshill** [comment]
Oh also, is your GitHub repo public?

**Comment by maxferlauto** [comment]
Yup, looks good. My repo was private but I didn't really have a good reason for it to be. Now its public.

**Comment by apreshill** [comment]
thank you!

**Pull request merged**
